---
title: "HPB trials"
output:
  html_document: default
  pdf_document: default
---

```{r installation}
#devtools::install_github("RHESSys/RHESSysIOinR")
```


```{r requiredlibraries}
#these libraries load just fine in R w/in the container 
library(tidyverse)
library(RHESSysIOinR)
library(ggpubr)

```



### Input files    
Edit the **rhessys_ver** = path and file name to point to your new version of RHESSys    (in R chunk below)

Testing data
```{r}
#### TESTING trials 
setwd("repo/Testing_rhessys_ExampleFiles")

#rhessys_ver = "/Users/naomitague/Model/RHESSys/rhessys/rhessys7.3"
#rhessys_ver = "/RHESSys/rhessys7.5" #from trials w/ Quinn
rhessys_ver = "../../rhessys7.5" #new to point backwards to model
worldfile = "worldfiles/w8TC.world"
header = "worldfiles/w8TC.hdr"
flowtable = "flowtables/w8TC.flow"
tecfile = "tecfiles/tec.test" 

#testing worldfiles I remade form their spatial data
rhessys_ver = "../../rhessys7.5" #new to point backwards to model
worldfile = "w8TC_dwh4.world"
#worldfile = "worldfiles/w8TC.world"
header = "worldfiles/w8TC.hdr"
#flowtable = "flowtables/w8TC.flow"
flowtable = "w8TC_dwh4.flow"
tecfile = "tecfiles/tec.test" 

##IOinR examples
#https://github.com/RHESSys/RHESSysIOinR/blob/main/vignettes/IOin_examples.Rmd

```


HPB data
```{r setrunvars}

#can run 'ls()' in powershell R to see what is in the environment 


# ### FOR CCR
# setwd("repo")
# 
# rhessys_ver = "../rhessys7.5" #new to point backwards to model
# worldfile = "CCR_files/worldfiles/ccr.world"
# header = "CCR_files/worldfiles/ccr.hdr"
# flowtable = "CCR_files/flowtables/ccr.flow"
# tecfile = "tecfiles/tec.test" #can maybe ignore for now


### FOR HPB
#NOTE: currently using patches and worldfile based on a basin output and not patchcl, for speedier runs
setwd("repo/HPB_files_clean")

#with testing defs and veg
# rhessys_ver = "../../rhessys7.5" #new to point backwards to model
# worldfile = "worldfiles/hpb.world"
# header = "worldfiles/hpb.hdr"
# flowtable = "flowtables/hpb.flow"
# tecfile = "tecfiles/tec.test" 

setwd("repo/HPB_files_clean")

#updating veg type to decid and soil to silty loam
rhessys_ver = "../../rhessys7.5" #new to point backwards to model
worldfile = "worldfiles/hpb2.world"
header = "worldfiles/hpb.hdr"
flowtable = "flowtables/hpb2.flow"
tecfile = "tecfiles/tec.test" 




```

#### Creates the command line
Currently this is just the same from the Testing script
```{r commandlinegen}

#original command line from testing
# cmd1 = sprintf("%s -t %s -w %s -whdr %s -r %s",
#                      rhessys_ver, tecfile, worldfile, header, flowtable)
 # cmd2 = sprintf("-pre out/test -s 0.355794 651.390265 -sv 0.355794 651.390265 -svalt 1.083102 1.193924, -gw 0.116316 0.916922")
# cmd3 = sprintf("-st 1988 10 1 1 -ed 2000 10 1 1 -b -g")
# command_line = paste(cmd1,cmd2,cmd3)

##cmd winner so far
#cmd2 = sprintf("-pre out/HPBtest -s 0.355794 651.390265, -gw 0.116316 0.916922")

# cmd3 = sprintf("-st 1908 01 1 1 -ed 2025 06 1 1 -b -g")


rhessys_ver = "../../rhessys7.5" #new to point backwards to model
worldfile = "worldfiles/hpb2.world"
header = "worldfiles/hpb.hdr"
flowtable = "flowtables/hpb2.flow"
tecfile = "tecfiles/tec.test" 


cmd1 = sprintf("%s -t %s -w %s -whdr %s -r %s",
                     rhessys_ver, tecfile, worldfile, header, flowtable)
cmd2 = sprintf("-pre out/HPBtest -s 0.9 650, -gw 0.1 0.9")
 cmd3 = sprintf("-st 1720 01 1 1 -ed 2025 06 1 1 -b -g")
command_line = paste(cmd1,cmd2,cmd3)

system(command_line)


```

### Run RHESSys
```{r runrhessys}
system(command_line)
```





### Read in the test results 

```{r}
getwd()

##read in validation data
validation_df <- read.csv("../Data_PreProcessing/HPB_stage_chem_data.csv") |> 
  mutate(Date = ymd(Date))


## this was originally output in repo/out, but i moved into dated folder
#hpb_test = readin_rhessys_output("../out/hpb_19oct25/test") #first run
#hpb_test = readin_rhessys_output("out/6nov25_910/HPBtest")
hpb_test = readin_rhessys_output("out/HPBtest") #most recent run that hasn't been moved to a folder

#DWH trials 
names(hpb_test)
hpb_test_bd <- hpb_test$bd
hpb_test_bdg <- hpb_test$bdg

output <- left_join(hpb_test_bd, hpb_test_bdg, 
                    by = c("day", "month", "year", "basinID", "wy", "yd", "date")) |> 
  select(day, month, year, date, yd, wy, basinID, everything()) |> 
  left_join(validation_df, by = c("date" = "Date"))





## Figuring out what duped columns exist between outputs, was calling output 'zed' for this
# colnames(zed)
# 
# zed |> 
#   select(1:5, lai.y, lai.x, gpsn.x, gpsn.y, plantc.x, plantc.y, litrc.x, litrc.y)
#   ggplot()
#   
#   get_duplicated_stems <- function(df) {
#   # Remove .x/.y suffixes
#   base_names <- sub("\\.(x|y)$", "", colnames(df))
#   
#   # Find duplicated stems
#   dupes <- base_names[duplicated(base_names) | duplicated(base_names, fromLast = TRUE)]
#   
#   unique(dupes)
# }
# 
# # Usage
# get_duplicated_stems(zed)


```


## Plot results 

stabilization plots 

```{r}

## Biogeochem Plots
output |> 
  filter(date > ymd("1900-01-01")) |> 
  select(date, year, yd, lai.x, #surfaceN, 
         litrc.x, plantc.x, soilc, streamflow_DON, streamflow_DOC,
         streamflow_NO3, streamflow_NH4
         ) |> 
  #filter(streamflow_DOC < 0.00001) |> 
  pivot_longer(-c(1:3)) |> 
  ggplot(aes(x = date, y = value))+
  geom_point()+ 
  facet_wrap(~name, scales = "free_y", ncol = 2)


## Hydro plots
output |> 
  # filter(date > ymd("1980-01-01")) |> 
  # select(date, year, yd, streamflow, baseflow, precip, recharge, unsat_stor, 
  #        rz_storage, sat_def, 
  #        litter_store, litter_capacity, 
  #        evap, evap_can, evap_lit, evap_soil,
  #        gw.Qout, gw.storage
  #        ) |> 
  select(date, year, yd, 
         streamflow,  precip, recharge, 
         unsat_stor, evap, gw.storage
         ) |> 
  pivot_longer(-c(1:3)) |> 
  ggplot(aes(x = date, y = value))+
  geom_point()+ 
  facet_wrap(~name, scales = "free_y", ncol = 2)


```


Validation to our data

```{r}

#streamflow by year
output |> 
  filter(wy > 2020) |> 
  select(date, year, yd, streamflow, precip) |> 
  pivot_longer(-c(1:3)) |> 
  ggplot(aes(x = yd, y = value, color = as.factor(year) ))+
  geom_line(size = 1.2)+
  facet_wrap(~name, scales = "free_y", nrow = 2)


#HPB watershed is 1.76 miles^2
#square miles to square meters = 1 square mile is 2.59e+6 square meters
#streamflow from model is in mm (mm to m ==  mm/1000)
rhessys_Q <- output |> 
  filter(year > 2020) |> 
  select(date, year, yd, streamflow, precip, flowmate_L_s, Q_L_s_stage) |> 
  mutate(streamflow_cmday = (streamflow / 1000 ) * (1.76 * 2590000),
         streamflow_cms = streamflow_cmday / 86400
         ) |> 
  mutate(rhessys_Q_L_s = streamflow_cms * 1000)


rhessys_Q |> 
  filter(date >= ymd("2024-01-01")) |> 
  select(date, rhessys_Q_L_s, Q_L_s_stage ) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = date, y = value, color = name))+
  geom_line(size = 1.2)+
  theme_bw()+
  labs(x = "Date", y = "Discharge (L/s)")
  
rhessys_Q |> 
  ggplot()+
  geom_line(aes(x = date, y = rhessys_Q_L_s), size = 1)+
  geom_point(aes(x = date, y = flowmate_L_s), color = "red", size = 3)+
  theme_bw()+
  labs(x = "Date", y = "Discharge (L/s)")

      
# left_join(rhessys_Q, ccr_flowmate, by = c("date" = "Date")) |> 
#   filter(date >= ymd("2023-01-01")) |> 
#   rename(Flowmate_L_s = L_s) |> 
#   select(date, rhessys_Q_L_s, Flowmate_L_s) |> 
#   rename(modeled = rhessys_Q_L_s,
#          observed = Flowmate_L_s) |> 
#   pivot_longer(-1) |> 
#   ggplot(aes(x = date, y = value, color = name))+
#   geom_point()+
#   theme_bw()



###NO3 conversions check
#assuimg gN/m2/day
output |> 
  filter(year > 2020) |> 
  select(date, year, yd, streamflow, precip, streamflow_NO3, NO3NO2_ugL) |> 
  mutate(NO3_mgL_AL = NO3NO2_ugL / 1000) |> 
  mutate(streamflow_cmday = (streamflow / 1000 ) * (1.76 * 2590000),
         streamflow_cms = streamflow_cmday / 86400
         ) |> 
  mutate(rhessys_Q_L_s = streamflow_cms * 1000) |> 
  mutate(NO3_gN_day = streamflow_NO3 * (1.76 * 2590000)) |> 
  mutate(Q_L_day = rhessys_Q_L_s * 86400) |> 
  mutate(NO3_g_L = NO3_gN_day / Q_L_day) |> 
  mutate(NO3_mg_L = NO3_g_L * 1000) |> 
  ggplot(aes(x= date, y = NO3_mg_L))+
  geom_point()+
  geom_point(aes(x= date, y = NO3_mgL_AL ), color = "red")

#assuimg kgN/m2/day
output |> 
  filter(year > 2020) |> 
  select(date, year, yd, streamflow, precip, streamflow_NO3) |> 
  mutate(streamflow_cmday = (streamflow / 1000 ) * (1.76 * 2590000),
         streamflow_cms = streamflow_cmday / 86400
         ) |> 
  mutate(rhessys_Q_L_s = streamflow_cms * 1000) |> 
  mutate(NO3_kgN_day = streamflow_NO3 * (1.76 * 2590000)) |> 
  mutate(Q_L_day = rhessys_Q_L_s * 86400) |> 
  mutate(NO3_kg_L = NO3_kgN_day / Q_L_day) |> 
  mutate(NO3_mg_L = NO3_kg_L * 1000000) |> 
  ggplot(aes(x= date, y = NO3_mg_L))+
  geom_point()

###DOC conversions check
output |> 
  #filter(year > 2020) |> 
  select(date, year, yd, streamflow, precip, streamflow_DOC, DOC_mgL) |>
  rename(DOC_mgL_AL = DOC_mgL) |> 
  mutate(streamflow_cmday = (streamflow / 1000 ) * (1.76 * 2590000),
         streamflow_cms = streamflow_cmday / 86400
         ) |> 
  mutate(rhessys_Q_L_s = streamflow_cms * 1000) |> 
  mutate(DOC_gC_day = streamflow_DOC * (1.76 * 2590000)) |> 
  mutate(Q_L_day = rhessys_Q_L_s * 86400) |> 
  mutate(DOC_g_L = DOC_gC_day / Q_L_day) |> 
  mutate(DOC_mg_L = DOC_g_L * 1000) |> 
  filter(DOC_mg_L < 20) |> 
  ggplot(aes(x= date, y = DOC_mg_L))+
  geom_point() +
  geom_point(aes(x= date, y = DOC_mgL_AL ), color = "red")




```

## For WVWA report back

```{r}

flowplot <-  rhessys_Q |> 
  filter(date >= ymd("2024-01-01")) |> 
  select(date, rhessys_Q_L_s, Q_L_s_stage ) |> 
  rename(modeled = rhessys_Q_L_s, observed = Q_L_s_stage) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = date, y = value, color = name))+
  geom_line(size = 1.2)+
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 months")+
  theme_bw()+
  labs(x = "Date", y = "Discharge (L/s)")


no3plot <- output |> 
  filter(date >= ymd("2024-01-01")) |> 
  select(date, year, yd, streamflow, precip, streamflow_NO3, NO3NO2_ugL) |> 
  mutate(NO3_mgL_AL = NO3NO2_ugL / 1000) |> 
  mutate(streamflow_cmday = (streamflow / 1000 ) * (1.76 * 2590000),
         streamflow_cms = streamflow_cmday / 86400
         ) |> 
  mutate(rhessys_Q_L_s = streamflow_cms * 1000) |> 
  mutate(NO3_gN_day = streamflow_NO3 * (1.76 * 2590000)) |> 
  mutate(Q_L_day = rhessys_Q_L_s * 86400) |> 
  mutate(NO3_g_L = NO3_gN_day / Q_L_day) |> 
  mutate(NO3_mg_L = NO3_g_L * 1000) |> 
  select(date, NO3_mg_L, NO3_mgL_AL) |> 
  rename(modeled = NO3_mg_L, observed = NO3_mgL_AL) |>
    filter(modeled < 300) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = date, y = value, color = name))+
  geom_point(size = 2)+
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 months")+
  theme_bw()+
  labs(x = "Date", y = "Nitrate (mg/L)")

library(patchwork)
flowplot / no3plot

```

LAI
```{r}
hpb_lat <- 37.3646
hpb_long <- -79.9733
## GET LAI data following Quinn's code
#https://frec-5174.github.io/eco4cast-in-R-book/neon-data.html#modis-lai
library(MODISTools)
lai <- MODISTools::mt_subset(product = "MCD15A2H",
                  lat = hpb_lat,
                  lon =  hpb_long,
                  band = c("Lai_500m", "FparLai_QC"),
                  start = as_date("2020-01-01"),
                  end = Sys.Date(),
                  site_name = "HPB",
                  progress = FALSE)


lai_cleaned <- lai |> 
  mutate(scale = ifelse(band == "FparLai_QC", 1, scale),
         scale = as.numeric(scale),
         value = scale * value,
         datetime = lubridate::as_date(calendar_date)) |> 
  select(band, value, datetime) |> 
  pivot_wider(names_from = band, values_from = value) |> 
  filter(FparLai_QC == 0) |> 
  rename(observation = Lai_500m) |> 
  mutate(variable = "lai") |> 
  select(datetime, variable, observation)



### plot lai
lai_cleaned <- lai_cleaned |> 
  pivot_wider(names_from = variable, values_from = observation) |> 
  rename(lai_MODIS = lai)

lai_cleaned |> ggplot(aes(x = datetime, y = lai_MODIS))+ geom_point()


###join to RHESSys output
# did a quick check and lai.x always equals lai.y
lai_fig <- output |> 
  filter(year(date) > 2019) |> 
  left_join(lai_cleaned, by = c("date" = "datetime")) |> 
  select(date, lai.x, lai_MODIS) |> 
  rename(modeled = lai.x,
         observed = lai_MODIS) |> 
  pivot_longer(-1) |> 
  # filter(date >= ymd("2024-01-01")) |> 
  ggplot(aes(x = date, y = value, color = name))+
  geom_line()+
  geom_point(size = 2)+
  # scale_x_date(date_labels = "%b %Y", date_breaks = "3 months")+
  scale_x_date(date_labels = "%Y", date_breaks = "1 year")+
  theme_bw()+
  labs(x = "Date", y = "Leaf Area Index (LAI)")

lai_fig

flowplot/lai_fig


```



## Look at CCR flowmate data

```{r}
# #read in data
# Qedi <- read.csv("https://pasta.lternet.edu/package/data/eml/edi/454/8/5edb79c2676d7b351d9eec184799c7dd")
# qL1 <- read.csv("https://raw.githubusercontent.com/CareyLabVT/Reservoirs/refs/heads/master/Data/DataNotYetUploadedToEDI/Raw_Discharge/ManualDischarge_L1.csv")
# 
# #filter to hpb
# ccr_flowmate <- rbind(Qedi, qL1) |> 
#   filter(Reservoir == "CCR", 
#          #Site == 101,
#          Site %in% c(100,101)
#         ) |>
#   mutate(DateTime = ymd_hms(DateTime),
#           Date = as.Date(DateTime)) |> 
#   mutate(L_s = Flow_cms * 1000) 
# 
# 
# #plot of flowmate data 
# ccr_flowmate |> ggplot(aes(x = Date, y = L_s))+ 
#   geom_point()+ geom_line()



```



```{r}

# #read in original climate files as a check
# getwd()
# 
# ccrclim <- read_clim("clim/ccr_daily")
# 
# ccrclim |> 
#   mutate(Date = ymd(date)) |> 
#   filter(Date >= ymd("1989-10-01"),
#          Date <= ymd("2000-09-30")) |> 
#   select(Date, rain, tmin, tmax) |> 
#   pivot_longer(-1)  |> 
#   ggplot(aes(x = Date, y = value))+
#   geom_point()+
#   facet_wrap(~name, scales = "free_y")
```




